POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "I am hodddnestyddddddddddd",
    "author": "Bloodsadsbastard",
    "likes": 69,
    "url" : "www.csadasom",
    "userId" : "60cd916cc8606753b62df4d2"
}

###############


POST http://localhost:3003/api/login
content-type: application/json

{
    "username" : "gatsby",
    "password" : "gatsby"
}


#############

PUT http://localhost:3003/api/blogs/60c89166a7747d999666acdf
content-type: application/json

{
    "id": "60c89166a7747d999666acdf",
    "title": "I am a liar",
    "author": "Bloodbastard",
    "likes": 69
}

###################
DELETE http://localhost:3003/api/blogs/60c89166a7747d999666acdf


########
POST http://localhost:3003/api/users
content-type: application/json

{
    "name" : "hymen",
    "username" : "grotesque",
    "password" : "grotesque"

}

##############


POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdhbmVzZmFhc2gxMiIsImlkIjoiNjBjZGQ1OTBiZGJmOTgyYWYzZmJkNDYwIiwiaWF0IjoxNjI0MTAyMzA5fQ.79Wo4d0fDNXohX6ImEhPNINPqORMRjzrEzodcVG3Eg4

{
    "title": "I am hodddnestyddddddddddd",
    "author": "Bloodsadsbastard",
    "likes": 69,
    "url" : "www.csadasom"

}
