POST http://localhost:3003/api/blogs
Authorization : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2MTFjZTA0NjhkODRlMDUzODc0MTc2YTIiLCJpYXQiOjE2MjkzOTY1MzZ9.SiH0fj2hzZ-5MhxkCqKwcXSFZiDAhD3ozACM3zHkGsc
{
    "title": "I am hodddnestyddddddddddd",
    "author": "Bloodsadsbastard",
    "likes": 69,
    "url" : "www.csadasom",
    "userId" : "60cd916cc8606753b62df4d2"
}

###############


POST http://localhost:3002/api/login
content-type: application/json

{
    "username" : "user1",
    "password" : "user1pass"
}


#############

PUT http://localhost:3003/api/blogs/611ced3275c2caa965ead167
content-type: application/json

{
    "id": "60c89166a7747d999666acdf",
    "title": "I am a liar",
    "author": "Bloodbastard",
    "likes": 69
}

###################
DELETE http://localhost:3003/api/blogs/611ceeb92770acaedaac443a
Content-Type: application/json
Authorization: bearer eyJhbGciOiJtrUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2MTFjZTA0NjhkODRlMDUzODc0MTc2YTIiLCJpYXQiOjE2MjkyODMyNjl9.NvYKW2nimXrqrnnHVznoiCXFW7tpOsZ4qQ7PKtBYBiI

########
POST http://localhost:3001/api/users
content-type: application/json

{
    "name": "username",
    "username" : "user1",
    "password" : "user1pass"
}

##############


POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2MTFjZTA0NjhkODRlMDUzODc0MTc2YTIiLCJpYXQiOjE2MjkyODMyNjl9.NvYKW2nimXrqrnnHVznoiCXFW7tpOsZ4qQ7PKtBYBiI

{
    "title": "Roman Athelte",
    "author": "Have you been drinking?",
    "likes": 69,
    "url" : "www.csadasom"

}
