DELETE https://boiling-springs-96480.herokuapp.com/api/persons/


#####
GET https://boiling-springs-96480.herokuapp.com/api/persons/1

#########
GET http://localhost:3001/api/persons


#####
POST http://localhost:3001/api/persons 
content-type: application/json

{
    "name" : "ramesh Futane",
    "number" : 9881240202
}


#####
POST http://localhost:3001/api/persons 
content-type: application/json

{
    "name" : "Xavier Ramesh",
    "number" : "89784556512"
}